highlighter: rouge
permalink: /:title

title: Tom Brow
author: Tom Brow
url: https://tombrow.com

# Use CommonMark instead of Markdown to gain support for markdown within HTML.
# https://stackoverflow.com/a/29378250
markdown: CommonMarkGhPages


# This is required for jekyll-sitemap:
# https://github.com/jekyll/jekyll-sitemap/blob/master/README.md#usage
url: "https://tombrow.com"

# "If all gem plugins have the same priority, they will be executed in the
# order they are required, generally. Thus, if you have other plugins which
# generate content and store that content in site.pages, site.posts, or
# site.collections, be sure to require jekyll-sitemap either after those other
# gems if you want the sitemap to include the generated content, or before
# those other gems if you don't want the sitemap to include the generated
# content from the gems. "
plugins:
  - jekyll-feed
  - jekyll-sitemap
